### ISSUE TITLE
ZIO-like monad & transformer

### ISSUE THREAD

**Issue by bbarker** [purescript/purescript-transformers#114]
Similar to how RWST/RWS are present in this repository, I'm wondering if something like [ZIO](https://github.com/scalaz/scalaz-zio) might be a good fit here - or as a separate repository?

See this [short discussion](https://twitter.com/jdegoes/status/1133709221843759104?s=19).

Since it would likely need to depend on `Aff`, so that might be a reason to create a separate project, though I suppose the core type might still be useful for many SPA-like synchronous projects meant to run in the browser without the Aff dependency.

Now the easy part (hard part?): I suppose it could be called ZIO, but alternatively it could be called [Trio](https://github.com/snoyberg/trio) after the analogue in Haskell, or named similar to RWST:

REA: Reader / Error || Either / A || Aff?  - I guess this depends on the eventual architecture/implementation, though.

**Comment by hdgarrood** [comment]
It sounds like something which would be great to have, but I don't think it needs to be in core. I think a separate project is probably the best way forward. Have you seen [`purescript-rave`](https://github.com/reactormonk/purescript-rave/blob/master/src/Rave.purs) by the way?

**Comment by garyb** [comment]
I don't think it can be implemented on top of `Aff` exactly, since polymorphic error handling would need to be done there. @natefaubion is the man to talk to, I think he basically has a picture in his head of how it would work, but hasn't had the time / built up the energy to face working on the internals again. :wink:

**Comment by bbarker** [comment]
> It sounds like something which would be great to have, but I don't think it needs to be in core. 

:+1: 

>  Have you seen purescript-rave by the way?

Rave looks like a great starting point in any case. (Incidentally I had cloned it to first try out spago but had no idea what it was in that context!)

> I don't think it can be implemented on top of Aff exactly, since polymorphic error handling would need to be done there. @natefaubion is the man to talk to, I think he basically has a picture in his head of how it would work, but hasn't had the time / built up the energy to face working on the internals again

Understandable! Well I'm happy to know about Rave - I'll close this, but maybe link to any of my findings on Rave after I get a chance to use it.

**Comment by natefaubion** [comment]
https://github.com/purescript-contrib/purescript-aff/issues/137 for some discussion.

**Comment by garyb** [comment]
Ah thanks, I did glance at the issues but I guess I was looking for the wrong keyword.
