### ISSUE TITLE
Add IdentityT

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-transformers#120]
For context, this is included in the [Haskell 'transformers' library](https://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Identity.html#t:IdentityT)

**Comment by hdgarrood** [comment]
I'd prefer to wait until we have a concrete use case for it, personally.

**Comment by JordanMartinez** [comment]
I am trying to port hedgehog to PureScript and they use it. That's why I
opened this issue.
However, I can keep that code in the port until we have more use cases than
this.

**Comment by hdgarrood** [comment]
Ah okay, I reckon that probably counts. Can you describe how it's useful for your hedgehog port?

**Comment by JordanMartinez** [comment]
It is used to create 3 different type class instances and I'm guessing that `TreeT` is somehow affected by it:
- [TreeT definition](https://github.com/JordanMartinez/purescript-hedgehog/blob/purescriptPort/hedgehog/src/Hedgehog/Internal/Tree.purs#L86)
- [Distributive instance](https://github.com/JordanMartinez/purescript-hedgehog/blob/purescriptPort/hedgehog/src/Hedgehog/Internal/Distributive.purs#L46)
- [MonadGen instance](https://github.com/JordanMartinez/purescript-hedgehog/blob/purescriptPort/hedgehog/src/Hedgehog/Internal/Gen.purs#L358)
- [MonadTest instance](https://github.com/JordanMartinez/purescript-hedgehog/blob/purescriptPort/hedgehog/src/Hedgehog/Internal/Property.purs#L547)

**Comment by hdgarrood** [comment]
Instance definitions don't really justify the existence of IdentityT though, I think the part that's more relevant here is places where those instances would be used. I think perhaps similarly to how `identity` is useful for functions which take functions as arguments, `IdentityT` could be useful for types which take monad transformers as arguments. Does hedgehog have any of those?

**Comment by JordanMartinez** [comment]
> `IdentityT` could be useful for types which take monad transformers as arguments.

Yeah, that would make sense. Similar to how `Identity` acts like a placeholder monad argument.

After looking around a bit more, seems like [`distributeT` from `MonadTransDistributive`](https://github.com/JordanMartinez/purescript-hedgehog/blob/purescriptPort/hedgehog/src/Hedgehog/Internal/Distributive.purs#L26-L44) has a `MFunctor` constraint that takes a monad transformer as an argument. However, the purescript port of [mmorph's `MFunctor`](https://pursuit.purescript.org/packages/purescript-mmorph/5.1.0/docs/Control.Monad.Morph#t:MFunctor) doesn't have an instance for `IdentityT`. I imagine it's because `IdentityT` isn't included in this library. Does that concrete example suffice?

**Comment by hdgarrood** [comment]
Yep, that works for me.

**Comment by JordanMartinez** [comment]
I can submit a PR for this. However, what should the file's module name be? `Control.Monad.Identity.Trans`?

**Comment by hdgarrood** [comment]
Yep, that conforms to the convention we're using in this library.
