### ISSUE TITLE
Change Eff to Effect in example

### ISSUE THREAD

**Issue by ursi** [purescript/purescript-transformers#127]
The example for [MonadCont](https://pursuit.purescript.org/packages/purescript-transformers/4.2.0/docs/Control.Monad.Cont.Class#t:MonadCont) uses `Eff`. I would put in a PR to change this except I still don't understand how this works, (partially because I don't know how `Eff` works so it's harder to figure out :p)

**Comment by JordanMartinez** [comment]
`Eff (a :: SOMETHING | r) outputValue` is the same as `Effect outputValue`.

**Comment by mhmdanas** [comment]
This seems to be mostly done. The only other placed where `Eff` is used(?) is in the name of this module: https://github.com/purescript/purescript-transformers/blob/87bd95f8ca68b7710f3e45c16fb9bb3e74c7f723/test/Example/StateEff.purs#L1
If this should be changed, I'll submit a PR. If not, then this issue should be closed.

**Comment by JordanMartinez** [comment]
@ursi Please submit a PR making this change.

**Comment by ursi** [comment]
@JordanMartinez Which change exactly? Someone has changed the documentation for MonadCont. Are you asking me to change `Example.StateEff` as mhmdanas pointed out?

**Comment by JordanMartinez** [comment]
Ah... I didn't know that. I assumed someone would have updated this issue if they had done that.

I don't think the module name change is needed. What we gain isn't worth the time spent on it. I'm going to close this issue.

**Comment by ursi** [comment]
I actually currently have a different PR right now for this same documentation. I would have closed this issue earlier but I totally forgot about it.
