### ISSUE TITLE
Modify the definition of the `asks` function of `ComonadEnv`.

### ISSUE THREAD

**Issue by mutex-w** [purescript/purescript-transformers#130]
The current definition is more restrictive than necessary. Modify as follows.

from
`asks :: forall e1 e2 w. ComonadEnv e1 w => (e1 -> e2) -> w e1 -> e2`
to
`asks :: forall e1 e2 w a. ComonadEnv e1 w => (e1 -> e2) -> w a -> e2`

The Haskell definition is as follows.
`asks :: ComonadEnv e w => (e -> e') -> w a -> e'`

**Comment by mutex-w** [comment]
Also, `ComonadAsk` instead of `ComonadEnv` may be sufficient.

**Comment by garyb** [comment]
:+1: to both suggestions.

I'd say `asks`'s type is a bug even, it makes no sense to require `w e1`, probably makes the function unusable most of the time.
