### ISSUE TITLE
Remove Error class constraint on ErrorT

### ISSUE THREAD

**Issue by singpolyma** [purescript/purescript-transformers#20]
Or provide ExceptT/EitherT -- this typeclass constraint was originally a result of the monad fail function in Haskell, and the latest Haskell transformers package is deprecating it -- I vote we just remove it here, simplifies things a lot.

**Comment by paf31** [comment]
I'd like to revisit this. I think it would be good to move to `ExceptT`.

**Comment by garyb** [comment]
We now have both.
