### ISSUE TITLE
0.7.0 isn't treated as a pre-release version

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-transformers#51]
Bower won't treat 0.7.0 as a pre-release version; should it have been released as 0.7.0-rc.1 instead?

For example, `bower i purescript-transformers` will currently select 0.7.0, but I expect we would rather it install 0.6.1, at least for the time being.

**Comment by garyb** [comment]
Phil has made the `-rc.n` revisions but the old `0.7.0` tag was still active, so I've just deleted it. We should probably release it as `0.7.1` when we do to ensure there's no caching issues.

**Comment by hdgarrood** [comment]
Cool, thanks. I guess this issue can be closed now then?
