### ISSUE TITLE
Apply and Applicative instance of ExceptT are inconsistent

### ISSUE THREAD

**Issue by xuwei-k** [purescript/purescript-transformers#60]
- https://github.com/purescript/purescript-transformers/blob/v0.8.1/src/Control/Monad/Except/Trans.purs#L53-L60
- https://github.com/scalaz/scalaz/pull/255

**Comment by hdgarrood** [comment]
I don't understand. Is it really Apply and Applicative, or Monad and Applicative? Can you provide an example that demonstrates the inconsistency?
