### ISSUE TITLE
MonadError Error (Eff e) instance?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-transformers#65]
Do you think this would work? It would certainly be nice to have. Might require a little bit of `unsafeInterleaveEff` because of the duplicate row issue.

**Comment by paf31** [comment]
This could be nice to have for sure, but it won't be possible to constrain the row of effects to contain `EXCEPTION` right now. Maybe after `~` constraints get added?

**Comment by hdgarrood** [comment]
:+1:

**Comment by hdgarrood** [comment]
Once we have this, I would love for there to be a `throw :: forall m a. (MonadError Error m) => String -> m a` defined somewhere, which is just `throwError <<< error`. So then it could be used for both `Eff` and `Aff`.

**Comment by natefaubion** [comment]
This can be done now with `EffectRowEquals`.

**Comment by rubenpieters** [comment]
I have a possible implementation here: https://github.com/rubenpieters/purescript-transformers/commit/e238c61fd8dc30387bf5c414e4b9d8941d2f268c

Some notes:
- I had to add `unsafeCoerceEff`, not sure of other/better possibilities to make the eff labels work out
- Using `catchError` means that the `exception :: EXCEPTION` label sticks around

**Comment by rubenpieters** [comment]
If you want I can open a PR and the discussion can be moved there

**Comment by hdgarrood** [comment]
I think at this point it might be best to actually just leave it until 0.12, when we will start using `Effect :: Type -> Type` by default instead of `Eff`.

**Comment by rubenpieters** [comment]
Ok, that makes sense.

**Comment by hdgarrood** [comment]
I'll close this, since a 0.12 RC is now out.
