### ISSUE TITLE
ListT.scanl broken?

### ISSUE THREAD

**Issue by DanielGronau** [purescript/purescript-transformers#72]
I didn't try it out, just "translated" it, but it looks like line 218 in https://github.com/purescript/purescript-transformers/blob/v1.0.0/src/Control/Monad/List/Trans.purs should read

`h (Yield a s) = let b'' = f b' a in Just $ Tuple (Tuple b'' (force s)) b''`

Note the use of `b'` instead of `b`, which make IMHO no sense in this context.

**Comment by paf31** [comment]
Yes, this definitely looks incorrect.
