### ISSUE TITLE
Export runListT? 

### ISSUE THREAD

**Issue by kozak** [purescript/purescript-transformers#83]
Should runListT be exported? I stumbled on this when going through this: 
https://github.com/Gabriel439/Haskell-List-Transformer-Library/blob/master/src/List/Transformer.hs 
where runListT is used. 

Ok it seems its a different runListT - so it probably shouldn't be exported.

**Comment by matthewleon** [comment]
It does seem bizarre that the library defines `runListT` and then seems to do nothing with it.

**Comment by paf31** [comment]
It should be removed since `ListT` has a `Newtype` instance now.

**Comment by garyb** [comment]
> It should be removed since `ListT` has a `Newtype` instance now.

It looks like there is a bug here... `ListT`'s constructor is not exported, nor is `Step`, the inner type, so I don't think that `Newtype` instance should be allowed.

**Comment by matthewleon** [comment]
Is the correct approach to export just the constructor and remove the `Newtype` instance? That would be breaking.

**Comment by garyb** [comment]
We'll be doing some breaking updates soon anyway... but there is a non-breaking solution too: export the stuff that is hidden!

I think I asked @paf31 about it before and he thought that it was better to keep it private though.

**Comment by matthewleon** [comment]
At the very least, for consistency with the other transformers, it seems to me that `runListT` should indeed be exported. I imagine that @paf31 has some good reason for keeping it this way?

As for not exposing the `ListT` constructor, that makes some sense, as `nil`, `singleton`, `unfold` etc. provide ample ways to enter the monad.

**Comment by matthewleon** [comment]
(adding to the above, perhaps what we _really_ want is some modified version of `runListT` that "unrolls" the monad into a list, strict or lazy, in the parent monad?)

**Comment by matthewleon** [comment]
https://hackage.haskell.org/package/list-t-1/docs/ListT.html

For reference, the above package provides such facilities as `toList`.

**Comment by paf31** [comment]
> I think I asked @paf31 about it before and he thought that it was better to keep it private though.

I think it's probably fine, especially since we have a `Newtype` instance anyway now. Let's just export the constructor.

**Comment by kozak** [comment]
In the Gabriel's library  'runListT :: Monad m => ListT m a -> m ()' is described as 'Use this to drain a `ListT`, running it to completion and discarding all values.  And I think something like this should work: 
```

**Comment by paf31** [comment]
I think you would need `foldl'` at least, but there's no reason we couldn't provide that function.
