### ISSUE TITLE
evalStateT vs. execStateT

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-transformers#87]
It would be nice for some clarification as to why both of these exist, and whether one is to be preferred over another.

**Comment by garyb** [comment]
I'm not sure how it could be further clarified, given the types and existing descriptions for the functions - any suggestions? They're just `fst` and `snd` over `runStateT`.

**Comment by matthewleon** [comment]
Actually, no. I just failed to notice that the final type var in the declarations is different. My apologies.

**Comment by garyb** [comment]
No problem :smile:
