### ISSUE TITLE
Add attempt

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-transformers#94]
I find this function very useful:

```purescript
attempt :: forall m e a. MonadError e m => m a -> m (Either e a)
attempt a = (Right <$> a) `catchError` (pure <<< Left)
```

This makes it easier to "not catch more than you need". For example when you want to catch only exceptions thrown by `a`, and not by `b`, there is no reasonable way to do this without `attempt`:

```purescript
attempt a >>= either e b

-- vs overly defensive

(a >>= b) `catchError` e
```

**Comment by paf31** [comment]
This is the same as `try` from `Control.Monad.Exception` so I think we should call this `try` as well.

**Comment by rightfold** [comment]
👍🏻

Sent from my iPhone.
